/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import Koneksi.Koneksi;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 *
 * @author Ervinanurul
 */
public class camera extends javax.swing.JFrame {
   
    Dimension d = Toolkit.getDefaultToolkit().getScreenSize(); 
    Connection conngui = new Koneksi().getKoneksi();
    DefaultTableModel model;
    
    public camera() {
        initComponents();
        
        setLocation(d.width / 2 - getWidth() / 2, d.height / 2 - getHeight() / 2);
        
        String [] judul = {"id","Nama", "Jenis", "Merek", "Lensa", "Harga", "Keterangan"  };
        model = new DefaultTableModel(judul, 0);
        tabel_camera.setModel(model);
        tampilkeunn();
    }

    private void reset() {
    id.setText("");
    nama.setText("");
    jenis.setText("");
    merek.setText("");
    lensa.setText("");
    harga.setText("");
    keterangan.setText("");
    }
    
     private void tampilkeunn() {
      int row = tabel_camera.getRowCount();
        for (int a = 0; a < row; a++) {
        model.removeRow(0);
        }
        
        try {
            conngui = Koneksi.getKoneksi();
            ResultSet rs = conngui.createStatement().executeQuery("SELECT * FROM camera");
            
            while(rs.next()) {
                String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)};
                model.addRow(data);
            }
                
        } catch (Exception e) {
            
        }
    }
     
     private void cariData(String key){
        try{

            String [] judul = {"No","Nama", "Jenis", "Merek", "Lensa", "Harga", "Keterangan"  };
            model = new DefaultTableModel(null, judul);
            tabel_camera.setModel(model);
            
            conngui = Koneksi.getKoneksi();
            Statement stt=conngui.createStatement();
            model.getDataVector().removeAllElements();
            
            ResultSet RsProduk = stt.executeQuery("SELECT * from camera WHERE id LIKE '%"+key+"%' OR nama LIKE '%"+key+"%'");  
            while(RsProduk.next()){
                Object[] data={
                    RsProduk.getString("id"),
                    RsProduk.getString("Nama"),
                    RsProduk.getString("Jenis"),
                    RsProduk.getString("Merek"),
                    RsProduk.getString("Lensa"),
                    RsProduk.getString("Harga"),
                    RsProduk.getString("Keterangan")
                };
               model.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jenis = new javax.swing.JTextField();
        txtjenis = new javax.swing.JLabel();
        merek = new javax.swing.JTextField();
        jenis1 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jenis2 = new javax.swing.JLabel();
        jenis3 = new javax.swing.JLabel();
        keterangan = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_camera = new javax.swing.JTable();
        txtlensa = new javax.swing.JLabel();
        lensa = new javax.swing.JTextField();
        cari_proyektor_admin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        camera = new javax.swing.JMenu();
        proyektor = new javax.swing.JMenu();
        pengguna = new javax.swing.JMenu();
        logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 600));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel1.setText("DAFTAR PENYEWAAN CAMERA");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel2.setText("kode barang");

        id.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setText("Nama");

        nama.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jenis.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        txtjenis.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txtjenis.setText("Jenis");

        merek.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jenis1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jenis1.setText("Merek");

        harga.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jenis2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jenis2.setText("Harga sewa");

        jenis3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jenis3.setText("Keterangan");

        simpan.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        edit.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        hapus.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        batal.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        batal.setText("BATAL");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        tabel_camera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_camera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_cameraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_camera);

        txtlensa.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txtlensa.setText("Lensa");

        lensa.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        cari_proyektor_admin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cari_proyektor_adminKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setText("Cari");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jenis1))
                                        .addGap(84, 84, 84))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtjenis)
                                            .addComponent(jLabel2)
                                            .addComponent(txtlensa))
                                        .addGap(35, 35, 35)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nama)
                                    .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(jenis)
                                    .addComponent(merek)
                                    .addComponent(lensa))
                                .addGap(79, 79, 79)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jenis2)
                                    .addComponent(jenis3))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(harga, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(keterangan))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cari_proyektor_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel1)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jenis2)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(keterangan, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jenis3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtjenis)
                                .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jenis1)
                                .addComponent(merek, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lensa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlensa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cari_proyektor_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        home.setText("Home     ");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jMenuBar1.add(home);

        camera.setText("Camera     ");
        camera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cameraMouseClicked(evt);
            }
        });
        jMenuBar1.add(camera);

        proyektor.setText("Proyektor     ");
        proyektor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proyektorMouseClicked(evt);
            }
        });
        jMenuBar1.add(proyektor);

        pengguna.setText("Pengguna     ");
        pengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penggunaMouseClicked(evt);
            }
        });
        jMenuBar1.add(pengguna);

        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proyektorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proyektorMouseClicked
        proyektor p = new proyektor();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_proyektorMouseClicked

    private void cameraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraMouseClicked

    }//GEN-LAST:event_cameraMouseClicked

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed

    }//GEN-LAST:event_homeActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        home h = new home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void tabel_cameraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_cameraMouseClicked
        
        int i = tabel_camera.getSelectedRow();
        
        if(i > - 1) {
            id.setText(model.getValueAt(i, 0).toString());
            
            nama.setText(model.getValueAt(i, 1).toString());
                        
            jenis.setText(model.getValueAt(i, 2).toString());
            
            merek.setText(model.getValueAt(i, 3).toString());
            
            lensa.setText(model.getValueAt(i, 4).toString());
            
            harga.setText(model.getValueAt(i, 5).toString());
            
            keterangan.setText(model.getValueAt(i, 6).toString());
           
        }
    }//GEN-LAST:event_tabel_cameraMouseClicked

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        conngui = Koneksi.getKoneksi();
        try{
            
            String sql = "INSERT INTO camera VALUES " + "(" + "'"+id.getText()+ "'," + "'"+nama.getText()+ "'," + "'"+jenis.getText()+"'," + "'"+merek.getText()+"',"+ "'"+lensa.getText()+"',"+ "'"+harga.getText()+"',"+ "'"+keterangan.getText()+"'"+ ")";

            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            java.sql.PreparedStatement pst=conngui.prepareStatement(sql);
            pst.execute();
            tampilkeunn();
            
        } catch(Exception e){
            
            JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_simpanActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
    
    conngui = Koneksi.getKoneksi();
        
        try {
            
            String sql = "UPDATE camera SET id = '" +id.getText() + "', nama = '" + nama.getText() + "', jenis = '"+jenis.getText()+ "', merek = '"+ merek.getText() + "', lensa = '"+lensa.getText() + "', harga = '" +  harga.getText() + "', keterangan = '" + keterangan.getText() + "'" + "WHERE id = " + id.getText();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            java.sql.PreparedStatement pst=conngui.prepareStatement(sql);
            pst.executeUpdate(sql);
            tampilkeunn();
            reset();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        
        conngui = Koneksi.getKoneksi();
        
        int ok = JOptionPane.showConfirmDialog(null,"Anda Yakin Ingin Menghapus Data "+nama.getText()+"",".:: Konfirmasi ::.", JOptionPane.YES_NO_OPTION);
        if (ok==0) {
            try {
                String sql = "DELETE FROM camera WHERE id = '" + id.getText() + "'";            

                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                java.sql.PreparedStatement pst=conngui.prepareStatement(sql);
                pst.execute();
                tampilkeunn();
                reset();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Data Tidak Bisa Dihapus");
            }
            
        }
        
    }//GEN-LAST:event_hapusActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        reset();
    }//GEN-LAST:event_batalActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        login.admin_login ad_log = new login.admin_login();
        ad_log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void cari_proyektor_adminKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cari_proyektor_adminKeyReleased
        String key=cari_proyektor_admin.getText();
        System.out.println(key);

        if(key!=""){
            cariData(key);
        }else{
            tampilkeunn();
        }
    }//GEN-LAST:event_cari_proyektor_adminKeyReleased

    private void penggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penggunaMouseClicked
        pengguna p = new pengguna();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_penggunaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(camera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(camera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(camera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(camera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new camera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JMenu camera;
    private javax.swing.JTextField cari_proyektor_admin;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField harga;
    private javax.swing.JMenu home;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jenis;
    private javax.swing.JLabel jenis1;
    private javax.swing.JLabel jenis2;
    private javax.swing.JLabel jenis3;
    private javax.swing.JTextField keterangan;
    private javax.swing.JTextField lensa;
    private javax.swing.JMenu logout;
    private javax.swing.JTextField merek;
    private javax.swing.JTextField nama;
    private javax.swing.JMenu pengguna;
    private javax.swing.JMenu proyektor;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel_camera;
    private javax.swing.JLabel txtjenis;
    private javax.swing.JLabel txtlensa;
    // End of variables declaration//GEN-END:variables
}
